---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
spec:
  selector:
    matchLabels:
      app: customer-deployment
  template:
    metadata:
      labels:
        app: customer-deployment
    spec:
      containers:
        - name: customer-deployment
          image: com.food.ordering.system/customer.service:1.0-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-postgresql.default.svc.cluster.local:5432/postgres?currentSchema=customer&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: http://schema-registry.default.svc.cluster.local:8081
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: kafka.default.svc.cluster.local:9092
            - name: SPRING_DATASOURCE_PASSWORD
              value: minh00714124869
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer-deployment
  ports:
    - port: 8184
      targetPort: 8184
      name: customer-service-port
  type: LoadBalancer
  loadBalancerIP: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  selector:
    matchLabels:
      app: order-deployment
  template:
    metadata:
      labels:
        app: order-deployment
    spec:
      containers:
        - name: order-deployment
          image: com.food.ordering.system/order.service:1.0-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-postgresql.default.svc.cluster.local:5432/postgres?currentSchema=order&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: http://schema-registry.default.svc.cluster.local:8081
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: kafka.default.svc.cluster.local:9092
            - name: SPRING_DATASOURCE_PASSWORD
              value: minh00714124869
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: default
  labels:
    app: order-service
spec:
  selector:
    app: order-deployment
  ports:
    - name: order-service-port
      protocol: TCP
      port: 8181
  type: LoadBalancer
  loadBalancerIP: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  selector:
    matchLabels:
      app: payment-deployment
  template:
    metadata:
      labels:
        app: payment-deployment
    spec:
      containers:
        - name: payment-deployment
          image: com.food.ordering.system/payment.service:1.0-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-postgresql.default.svc.cluster.local:5432/postgres?currentSchema=payment&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: http://schema-registry.default.svc.cluster.local:8081
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: kafka.default.svc.cluster.local:9092
            - name: SPRING_DATASOURCE_PASSWORD
              value: minh00714124869
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: default
  labels:
    app: payment-service
spec:
  selector:
    app: payment-deployment
  ports:
    - name: payment-service-port
      protocol: TCP
      port: 8182
  type: LoadBalancer
  loadBalancerIP: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-deployment
spec:
  selector:
    matchLabels:
      app: restaurant-deployment
  template:
    metadata:
      labels:
        app: restaurant-deployment
    spec:
      containers:
        - name: restaurant-deployment
          image: com.food.ordering.system/restaurant.service:1.0-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-postgresql.default.svc.cluster.local:5432/postgres?currentSchema=restaurant&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: http://schema-registry.default.svc.cluster.local:8081
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: kafka.default.svc.cluster.local:9092
            - name: SPRING_DATASOURCE_PASSWORD
              value: minh00714124869
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  namespace: default
  labels:
    app: restaurant-service
spec:
  selector:
    app: restaurant-deployment
  ports:
    - name: restaurant-service-port
      protocol: TCP
      port: 8183
  type: LoadBalancer
  loadBalancerIP: ""

  #
  #zookeeper.default.svc.cluster.local, schema-registry.default.svc.cluster.local
